library(tidyverse)
library(janitor)
library(outbreaker2)
library(o2ools)
library(mixtree)
library(ape)
library(epitrix)
library(distcrete)
library(epicontacts)
library(visNetwork)
library(tidygraph)
library(ggraph)
library(patchwork)
library(knitr)
library(kableExtra)
library(httr2)
library(scales)
library(ggridges)
library(phangorn)
library(pheatmap)
library(ggtree)
library(coda)
library(purrr)
library(furrr)
library(future)
library(pipetime)

group_pal <- c(passenger = "#1f77b4", crew = "#d62728")
group_labels <- c(passenger = "Passenger", crew = "Crew")

set.seed(123)
